# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Digital Charlie
tagline:             'A blog for the work of Digital Charlie'
description:         'A blog for the writing and work of Digital Charlie.'
url:                 http://digitalcharlie.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Digital Charlie
  url:               https://twitter.com/furmanatorjr
  email:             furman.jr@gmail.com

# Custom vars
version:             1.0.0
