# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Digital Charlie
tagline:             'It's a blog and it has some writing.'
description:         'A blog for the work and writing of Charlie Furman.'
url:                 http://digitalcharlie.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Charlie Furman
  url:               https://twitter.com/furmanatorjr
  email:             furman.jr@gmail.com

# Custom vars
version:             awesome
