# Setup
title:               Digital Charlie
tagline:             'This is a blog and it has some writing.'
description:         'A blog for the work and writing of Charlie Furman.'
url:                 http://digitalcharlie.com
baseurl:             'http://digitalcharlie.com'
paginate:            5

# About/contact
author:
  name:              Charlie Furman
  url:               https://twitter.com/furmanatorjr
  email:             furman.jr@gmail.com

# Custom vars
version:             awesome
